FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN corepack enable pnpm && \
    pnpm install

# 1. 'pnpm run dev' starts the Vite server
# 2. '--host 0.0.0.0' tells Vite to be accessible from outside the container
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]